
export enum QarkAPICode {
  ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
  INVALID = "INVALID",
  ACCOUNT_IN_PROGRESS = "IN_PROGRESS",
  ACCOUNT_LINKING_SUCCESS = "ACCOUNT_LINKING_SUCCESS",
  ACCOUNT_LINKING_FAILED = "ACCOUNT_LINKING_FAILED"
}

export const POLLING_INTERVAL: number = 5000;
export const REQUEST_END_TIME: number = 5; // Number of minutes